server:
  port: 9999

spring:
  datasource:
    username: ${CHAOTIC_LIFE_USERNAME}
    password: ${CHAOTIC_LIFE_PASSWORD}
    url: ${CHAOTIC_LIFE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
mybatis:
  type-aliases-package: cc.greekn

